cleanup_entries:
  # Description of the service
  description: Clean up of dangling devices of the BLE Montitor integration.
parse_data:
  # Description of the service
  description: Send RAW HCI packet data to the BLE Montitor integration.
  fields:
    packet:
      name: Packet
      description: RAW HCI packet data hex
      required: true
      example: 043E2B02010000123456789ABC1F12161A1819416538C1A41B073915810B529F0F0B094154435F363534313139AA
